### ISSUE TITLE
Alcor Integration Progress Tracking

### ISSUE THREAD

**Issue by liangbin-pub** [futurewei-cloud/alcor-control-agent#152] opened 2020-10-21 22:45 UTC
Hi Zeta ACA team,

We will use this issue to capture USTC ACA integration progress, preferable consolidated into one itemized summary here before each end of day so we can capture and respond here in time.

Repo master, please assign this issue to all of us so we can get notified for update.

**Comment by er1cthe0ne** [comment] 2020-10-22 18:50
@HuaqingTu @zhangml @Zqy11 - as discussed in the opensource meeting, can you please provide an update on the work progress, questions on this github issue everyday end of day?

This will ensure the questions or any blocking were addressed quickly on the project. Thanks.

**Comment by zhangml** [comment] 2020-10-23 11:33
Hello,  Eric. I recently read part of the source code of ACA carefully. In order to better complete the issue, I would like to know which part of the ACA code should I pay more attention to?

**Comment by Zqy11** [comment] 2020-10-23 15:21
I used Docker and OVS to manually test the function of uploading the first package and installing the flows.
The test environment is as follows:

network node (as a gateway), 172.16.62.231:

computer node1,  172.16.62.237:
docker71, ip:192.168.1.71, tag=100
docker72, ip:192.168.1.72, tag=100

computer node2,  172.16.62.238:
docker81, ip:192.168.1.81, tag=100
docker82, ip:192.168.1.82, tag=100

I use ovs-docker to connect the container to the OVS and set tag:
# ovs-docker add-port br-tun eth0 docker81 --ipaddress=192.168.1.81/24
# ovs-vsctl set port d472714911294_l tag=100

I install the default flow table uploaded to the gateway on the compute nodes.
When the gateway receives the first packet, it forwards the packet. And I install the direct forwarding table flow in the source computing node.

**
But I meet a problem that the OVS flow table can not match the container's source ip, the following doesn't work:
# ovs-ofctl add-flow br-tun ip,nw_dst=192.168.1.81,priority=10,actions=output:3

But the computer nodes' ip can match:
# ovs-ofctl add-flow br-tun tun_src=172.16.62.237,priority=10,actions=output:vxlan238

I'm temporarily using the container's source mac address instead of ip matching:
# ovs-ofctl add-flow br-tun dl_src=b6:e1:35:5d:4e:bb,priority=10,actions=output:2
**

Next, I'll create several containers on the gateway to test the group table.

**Comment by HuaqingTu** [comment] 2020-10-23 15:22
Hi, Eric. I have update the zeta integration design. I have some questions.

1. Is the message sended from gateway node to compute node called OAM? So i need to specify how this message is handled by ACA and how ACA to configure flow table on ovs?
2. I also need to specify how ACA handle the message from Alcor server to configure flow table and group table?
3.  Bin said that each host has the information of ZGC to configure group table, so which part has this information? ACA, ovsdb or Nova?

**Comment by er1cthe0ne** [comment] 2020-10-24 00:38
> Hello, Eric. I recently read part of the source code of ACA carefully. In order to better complete the issue, I would like to know which part of the ACA code should I pay more attention to?

Hi @zhangml 

You can take a look at the flow of goal state message processing in ACA:

1. GoalStateProvisionerImpl::PushNetworkResourceStates - grpc receives the message
2. Aca_Comm_Manager::get_instance().update_goal_state - goal state message processing
3. Aca_Goal_State_Handler::get_instance().update_port_states
4. Aca_Goal_State_Handler::update_port_state_workitem
5. ACA_Dataplane_OVS::update_port_state_workitem
6. ACA_OVS_L2_Programmer::configure_port

The goal state message will be updated to include Zeta information - Alcor team (likely me) will take care of that.

Once ACA received this updated goal state message Zeta information, it needs to process the new Zeta information, figure out what information to store (in memory for now) and what openflow bucketing rules to program.

For the OAM processing path, you can take a look at how DHCP server code install the punt rule and process it:
1. ACA_Dhcp_Server::_init_dhcp_ofp - install the punt rule
2. ACA_OVS_Control::parse_packet - receive the punt OAM packet here, needs to parse it and then send it to our new code for processing and install the corresponding openflow rule. I don't think we need to store any information (in memory) for now. Note that we need to support deleting of the previously install openflow rules when we receives the corresponding OAM delete packet.
3. aca_dhcp_server::ACA_Dhcp_Server::get_instance().dhcps_recv - for reference on how dhcp code process a punt packet

**Comment by er1cthe0ne** [comment] 2020-10-24 00:57
> But I meet a problem that the OVS flow table can not match the container's source ip, the following doesn't work:

@Zqy11 - not sure why that doesn't work. But that's not a high priority as our design want to match the openflow rule based on port subnet, therefore, all ports within the same subnet will share the same set of rules. The direction to look into is to use "tag=100", so two ports from the same subnet will share the same tag, therefore, the bucket rules will be match based on "tag=100". e.g. the matching bucket rule may look similar to below code in ACA:

  cmd_string = "add-flow br-tun \"table=22,priority=1,dl_vlan=" + to_string(internal_vlan_id) +
               " actions=strip_vlan,load:" + to_string(tunnel_id) +
               "->NXM_NX_TUN_ID[]," + full_outport_list + "\"";

**Comment by er1cthe0ne** [comment] 2020-10-24 00:59
> Hi, Eric. I have update the zeta integration design. I have some questions.
> 
> 1. Is the message sended from gateway node to compute node called OAM? So i need to specify how this message is handled by ACA and how ACA to configure flow table on ovs?
> 2. I also need to specify how ACA handle the message from Alcor server to configure flow table and group table?
> 3. Bin said that each host has the information of ZGC to configure group table, so which part has this information? ACA, ovsdb or Nova?

@HuaqingTu - my reply to @zhangml above should give you some idea on the code flow. Let me look into your question and design doc more later tonight or over weekend.

**Comment by HuaqingTu** [comment] 2020-10-25 11:33
Hi, Erica. I'v update the document according to your suggestion and list my questions blow the PR. Next, I'll work on the workflow diagram on OAM handling.

**Comment by zhangml** [comment] 2020-10-26 12:53
I think we should add state about Zeta gateway to alcor's Goal state, such as GroupState. And add an interface similar to 
int update_group_state_workitem( const alcor::schema::SubnetState current_GroupState, alcor::schema::GoalStateOperationReply &gsOperationReply) = 0 in aca_dataplane_ovs.h.
Add the function of adding, deleting, modifying and checking the group table in OVS_Control.h:
int add_group(const char *bridge,  const string vpc_id, const string group_id, vector<string> gateways_ip);

int del_groups(const char *bridge,  const string vpc_id, const string group_id, bool strict)

void OVS_Control::dump_groups(const char *bridge, const char *flow, bool aggregate)

void OVS_Control::group_mod(const char *bridge, const char *flow, unsigned short int command)

And more implementation details will be added after the experimental test is completed.

**Comment by HuaqingTu** [comment] 2020-10-26 14:59
Hi, Eric. I've add some description about OAM packet handling and group rule delete. And also list my question blow the PR. Thanks for your patience.

**Comment by er1cthe0ne** [comment] 2020-10-28 06:04
@HuaqingTu @zhangml @Zqy11 - please provide an update on the work progress by end of day, we can make sure the questions and blocking issues are addressed quickly.

**Comment by HuaqingTu** [comment] 2020-10-28 14:42
Hi, Eric. I've update the document. Due to some configure errors about PlantUML in VS code on Windows, the figure is still draw with VISIO. I'll update the figure in PUML later. The rules in document is supported by Qianyu Zhang and the code change is supported by Minli Zhang. I have some questions:

1.Whether the tunnel between the host and the gateway is established after the ZGC information is issued by the Alcor server befor gateway path configuration ? Or when a host boots up, the tunnels between this host and all gateway nodes are built?

2. Are the installation of rules that match OAM packet after the configuration of gateway path is finished?

2.

**Comment by zhangml** [comment] 2020-10-29 11:26
I have summarized some of the bucket selection problems of the OVS group table select rule:

Information from OVS official website
Q: An OpenFlow “select” group isn’t dividing packets evenly among the buckets.
A: When a packet passes through a “select” group, Open vSwitch hashes a subset of the fields in the packet, then it maps the hash value to a bucket. This means that packets whose hashed fields are the same will always go to the same bucket[*]. More specifically, if you test with a single traffic flow, only one bucket will receive any traffic[**]. Furthermore, statistics and probability mean that testing with a small number of flows may still yield an uneven distribution.
[*] Unless its bucket has a watch port or group whose liveness changes during the test.
[**] Unless the hash includes fields that vary within a traffic flow, such as tcp_flags.

However, we have tested that continuous data packets in the same flow will be sent to the same bucket, but at different times the data packets may be sent to different buckets.

The source code for OVS group table selection is in the pick_default_select_group(struct xlate_ctx *ctx, struct group_dpif *group) on line 4563 of ofproto-dpif-xlate.c, and the hash algorithm used is in the group_best_live_bucket() function on line 1956. The source code of the hash algorithm is as follows:
static struct ofputil_bucket *
group_best_live_bucket(const struct xlate_ctx *ctx,
                       const struct group_dpif *group,
                       uint32_t basis)
{
    struct ofputil_bucket *best_bucket = NULL;
    uint32_t best_score = 0;

    struct ofputil_bucket *bucket;
    LIST_FOR_EACH (bucket, list_node, &group->up.buckets) {
        if (bucket_is_alive(ctx, bucket, 0)) {
            uint32_t score =
                (hash_int(bucket->bucket_id, basis) & 0xffff) * bucket->weight;
            if (score >= best_score) {
                best_bucket = bucket;
                best_score = score;
            }
            xlate_report(ctx, OFT_DETAIL, "bucket %"PRIu32": score %"PRIu32,
                         bucket->bucket_id, score);
        } else {
            xlate_report_bucket_not_live(ctx, bucket);
        }
    }

    return best_bucket;
}
I don't understand the function of LIST_FOR_EACH (bucket, list_node, &group->up.buckets). I have consulted the OVS developers and have not received a reply. I speculate that this macro definition may be the cause of the above test results.

**Comment by er1cthe0ne** [comment] 2020-10-30 05:08
> I have summarized some of the bucket selection problems of the OVS group table select rule:

@zhangml - thanks for the update. Let us know if you receive an update from the OVS developers (is there a link available?). I may look into the OVS code when I have time.

**Comment by er1cthe0ne** [comment] 2020-11-08 06:46
@HuaqingTu @zhangml @Zqy11 - please try to provide an update end of day Monday at your time, so that I can review and prepare answers before our next meeting. Thanks, Eric.

**Comment by HuaqingTu** [comment] 2020-11-09 13:13
Hi, Eric. I've learned how to use cmake, and viewed /build/aca-machine-init.sh and /src/CMakeLists.txt. Using the current shell script, I found librdkafka.a under /usr/lib/x86_64-linux-gnu, libpulsar.a under /usr/lib, and libopenvswitch.a under /usr/local/lib. But the static library of cppkafka is not found, I may need to modify the shell script to support the compilation of static library of cppkafka.

I have a question:
1. I found the following code in /src/CMakeLists.txt:

FIND_LIBRARY(RDKAFKA rdkafka /usr/lib/x86_64-linux-gnu NO_DEFAULT_PATH)
FIND_LIBRARY(CPPKAFKA cppkafka /usr/local/lib NO_DEFAULT_PATH)
FIND_LIBRARY(PULSAR pulsar /usr/lib NO_DEFAULT_PATH)
FIND_LIBRARY(OPENVSWITCH openvswitch /usr/local/lib NO_DEFAULT_PATH)
FIND_LIBRARY(MESSAGEMANAGER messagemanager ${CMAKE_CURRENT_SOURCE_DIR}/../include NO_DEFAULT_PATH)

But I didn't find the FIND_LIBRARY code about gRPC. So what do I miss?

**Comment by zhangml** [comment] 2020-11-09 13:35
Q: How does OVS divide flows among buckets in an OpenFlow “select” group?
A: In Open vSwitch 2.3 and earlier, Open vSwitch used the destination Ethernet address to choose a bucket in a select group. Open vSwitch 2.4 and later by default hashes the source and destination Ethernet address, VLAN ID, Ethernet type, IPv4/v6 source and destination address and protocol, and for TCP and SCTP only, the source and destination ports. The hash is “symmetric”, meaning that exchanging source and destination addresses does not change the bucket selection.
Select groups in Open vSwitch 2.4 and later can be configured to use a different hash function, using a Netronome extension to the OpenFlow 1.5+ group_mod message. For more information, see Documentation/group-selection-method-property.txt in the Open vSwitch source tree.

```
// ofproto/ofproto-dpif-xlate.c  line4649
static struct ofputil_bucket *
pick_select_group(struct xlate_ctx *ctx, struct group_dpif *group)
{
    /* Select groups may access flow keys beyond L2 in order to
     * select a bucket. Recirculate as appropriate to make this possible.
     */
    if (ctx->was_mpls) {
        ctx_trigger_freeze(ctx);
        return NULL;
    }

    switch (group->selection_method) {
    case SEL_METHOD_DEFAULT:
        return pick_default_select_group(ctx, group);
        break;
    case SEL_METHOD_HASH:
        return pick_hash_fields_select_group(ctx, group);
        break;
    case SEL_METHOD_DP_HASH:
        return pick_dp_hash_select_group(ctx, group);
        break;
    default:
        /* Parsing of groups ensures this never happens */
        OVS_NOT_REACHED();
    }

    return NULL;
}


// ofproto/ofproto-dpif-xlate.c  line4565
static struct ofputil_bucket *
pick_default_select_group(struct xlate_ctx *ctx, struct group_dpif *group)
{
    flow_mask_hash_fields(&ctx->xin->flow, ctx->wc,
                          NX_HASH_FIELDS_SYMMETRIC_L4);
    return group_best_live_bucket(ctx, group,
                                  flow_hash_symmetric_l4(&ctx->xin->flow, 0));
}



//  lib/flow.c  line2260
// default hash fields: dl_src,dl_dst, nw_src, nw_dst, nw_proto，vlan.tci
/* Hashes 'flow' based on its L2 through L4 protocol information. */
uint32_t
flow_hash_symmetric_l4(const struct flow *flow, uint32_t basis)
{
    struct {
        union {
            ovs_be32 ipv4_addr;
            struct in6_addr ipv6_addr;
        };
        ovs_be16 eth_type;
        ovs_be16 vlan_tci;
        ovs_be16 tp_port;
        struct eth_addr eth_addr;
        uint8_t ip_proto;
    } fields;

    int i;

    memset(&fields, 0, sizeof fields);
    for (i = 0; i < ARRAY_SIZE(fields.eth_addr.be16); i++) {
        fields.eth_addr.be16[i] = flow->dl_src.be16[i] ^ flow->dl_dst.be16[i];
    }
    for (i = 0; i < FLOW_MAX_VLAN_HEADERS; i++) {
        fields.vlan_tci ^= flow->vlans[i].tci & htons(VLAN_VID_MASK);
    }
    fields.eth_type = flow->dl_type;

    /* UDP source and destination port are not taken into account because they
     * will not necessarily be symmetric in a bidirectional flow. */
    if (fields.eth_type == htons(ETH_TYPE_IP)) {
        fields.ipv4_addr = flow->nw_src ^ flow->nw_dst;
        fields.ip_proto = flow->nw_proto;
        if (fields.ip_proto == IPPROTO_TCP || fields.ip_proto == IPPROTO_SCTP) {
            fields.tp_port = flow->tp_src ^ flow->tp_dst;
        }
    } else if (fields.eth_type == htons(ETH_TYPE_IPV6)) {
        const uint8_t *a = &flow->ipv6_src.s6_addr[0];
        const uint8_t *b = &flow->ipv6_dst.s6_addr[0];
        uint8_t *ipv6_addr = &fields.ipv6_addr.s6_addr[0];

        for (i=0; i<16; i++) {
            ipv6_addr[i] = a[i] ^ b[i];
        }
        fields.ip_proto = flow->nw_proto;
        if (fields.ip_proto == IPPROTO_TCP || fields.ip_proto == IPPROTO_SCTP) {
            fields.tp_port = flow->tp_src ^ flow->tp_dst;
        }
    }
    return jhash_bytes(&fields, sizeof fields, basis);
}

// ofproto/ofproto-dpif-xlate.c  line1955
static struct ofputil_bucket *
group_best_live_bucket(const struct xlate_ctx *ctx,
                       const struct group_dpif *group,
                       uint32_t basis)
{
    struct ofputil_bucket *best_bucket = NULL;
    uint32_t best_score = 0;

    struct ofputil_bucket *bucket;
    LIST_FOR_EACH (bucket, list_node, &group->up.buckets) {
        if (bucket_is_alive(ctx, bucket, 0)) {
            uint32_t score =
                (hash_int(bucket->bucket_id, basis) & 0xffff) * bucket->weight;
            if (score >= best_score) {
                best_bucket = bucket;
                best_score = score;
            }
            xlate_report(ctx, OFT_DETAIL, "bucket %"PRIu32": score %"PRIu32,
                         bucket->bucket_id, score);
        } else {
            xlate_report_bucket_not_live(ctx, bucket);
        }
    }

    return best_bucket;
}
```

**Comment by zhangml** [comment] 2020-11-09 14:13
After our test, the same flow will be mapped to the same bucket in the group table at any time. I will organize the test process and upload it later. @

**Comment by Zqy11** [comment] 2020-11-09 15:21
I have three updates recently:
(1) I implemented XDP demo, which can match IP addresses of two VMs and drop/pass packets.
(2) Due to the deadline of the paper, I am trying to identify the first packet in the gateway node. I can get the package uploaded to the gateway by using the veth pair.
(3) I use the following rules to identify unicast/multicast packets:
cookie=0xde84b1bb07dd2c12, duration=2243422.069s, table=2, n_packets=2213, n_bytes=241387, priority=0,dl_dst=00:00:00:00:00:00/01:00:00:00:00:00 actions=resubmit(,20)
 cookie=0xde84b1bb07dd2c12, duration=2243422.068s, table=2, n_packets=536, n_bytes=34161, priority=0,dl_dst=01:00:00:00:00:00/01:00:00:00:00:00 actions=resubmit(,22)
And then using 'arping' command to construct ARP broadcast packet and check n_packet.
But the specific functions to be realized and the requirements of ACA need to be discussed.

**Comment by Zqy11** [comment] 2020-11-11 14:50
I have three updates recently:
(1) Added unicast/multicast table.
     The implementation details and test results of unicast/multicast table is in issue-148 chapter 3.1.4/3.2.4 & chapter 5.
(2) Modified direct path rule.
     The implementation details and test results of direct path rule is in issue-148 chapter 6.
     Due to the randomness of TCP/UDP ports, I only match vlan_id(VNI), src_ip, dst_ip,  protocol and don't match src/dst port for the time being. 
     I tried to specify the src/dst port of sending packet, but the src/dst port of reply packet are still random. I'm writing a program to get the src/dst port of the upload packet at the gateway.
(3) I have realized a program to reply the uploaded ARP packet and at the gateway.

**Comment by er1cthe0ne** [comment] 2020-11-25 20:17
Let's use the individual issue/PR for our continue communication. Closing this one.

**Closed by er1cthe0ne** 2020-11-25 20:17 UTC
Labels: P1, Zeta, documentation
